Update repository to get rid of deprecated warnings and missing i383 architecture on newer distros
nymea/nymea-docs pull request #165
Opened 2022-11-07 17:57 UTC by t-mon

2022-11-08 09:09 UTC, mzanetti commented on src/pages/documentation/users/installation/core.md
> +sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/trusted.gpg.d/nymea.gpg --keyserver keyserver.ubuntu.com --recv-keys A1A19ED6
I don't think this is the proper way...

2022-11-15 13:40 UTC, t-mon commented on src/pages/documentation/users/installation/core.md
> +sudo gpg --homedir /tmp --no-default-keyring --keyring /etc/apt/trusted.gpg.d/nymea.gpg --keyserver keyserver.ubuntu.com --recv-keys A1A19ED6
updated

2022-11-16 09:08 UTC, mzanetti reviewed
Better, thanks!
I've added some suggestions for the wording.

2022-11-16 09:08 UTC, mzanetti commented on src/pages/documentation/developers/build-env.md
> +In order to make sure you get our packages, add the public repository singing key by running:
The packages in the nymea repository are signed with nymeas GPG key which can be imported by running:

2022-11-16 09:08 UTC, mzanetti commented on src/pages/documentation/developers/build-env.md
> +You can verify the fingerprint of your downloaded key file with following output:
Optionally, the keys fingerpring can be verified with:

2022-11-18 16:54 UTC, mzanetti commented on src/pages/documentation/users/installation/core.md
> +* riscv64
Just as a side note: riscv64 is currently only supported for ubuntu jammy and kinetic.
There is no debian stable for riscv64 yet (likely bookworm will include that thought).

2022-11-23 14:00 UTC, mzanetti approved these changes

2023-01-16 19:13 UTC, mzanetti requested changes

2023-01-16 19:13 UTC, mzanetti commented on src/pages/documentation/developers/build-env.md
> +echo "deb http://repository.nymea.io $(lsb_release -s -c) main" | sudo tee /etc/apt/sources.list.d/nymea.list
Hmmm... as someone on discord just pointed out, this is missing the the `deb-src` line which previously was added using the `-s` switch in apt-add-repository.

2023-01-16 19:15 UTC, mzanetti requested changes

2023-01-16 19:15 UTC, mzanetti commented on src/pages/documentation/developers/build-env.md
> -sudo apt-get update
Also the apt-get update step is missing now, which that user ran into and failed to installed build-deps...

2023-01-17 08:24 UTC, t-mon commented on src/pages/documentation/developers/build-env.md
> -sudo apt-get update
fixed, was a copy past error...

2023-01-17 10:06 UTC, mzanetti commented on src/pages/documentation/users/installation/app.md
> +To enable the repository, create a file named `/etc/apt/sources.list.d/nymea.list` using following command:
sorry, another small issue. there's a "the" missing now.

2023-03-08 09:30 UTC, merged